export const COMMAND_TYPES = {
  ADD_SHAPE: 'ADD_SHAPE',
  CHANGE_BORDER_COLOR: 'CHANGE_BORDER_COLOR',
  CHANGE_BORDER_WIDTH: 'CHANGE_BORDER_WIDTH',
  CHANGE_FILL_COLOR: 'CHANGE_FILL_COLOR',
  DELETE_SHAPE: 'DELETE_SHAPE',
  MOVE_SHAPE: 'MOVE_SHAPE',
};
